---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: download
  become: yes
  become_user: root
  get_url:
    url: '{{ duffle_url }}'
    dest: '{{ duffle_exe }}'
    mode: 0755
    checksum: '{{ duffle_checksum }}'
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ duffle_exe }}'
    dest: '{{ duffle_link }}'
    state: link
